import { Question } from './types';

// Banco de dados completo com 120 questões para o Simulado Detran
export const STATIC_QUESTIONS: Question[] = [
  // --- LEGISLAÇÃO E SINALIZAÇÃO (1-40) ---
  { id: 1, text: "Diante da placa (R-1), você entende que deve:", options: ["Seguir em frente", "Parar obrigatoriamente", "Dar preferência", "Reduzir a velocidade"], correctAnswer: 1, category: "Sinalização", explanation: "A placa R-1 indica Parada Obrigatória." },
  { id: 2, text: "É dever de todo condutor de veículo:", options: ["Dar passagem, pela esquerda, quando solicitado", "Buzinar ao cruzar uma faixa de pedestres", "Ultrapassar outro veículo pelo acostamento", "Transitar em velocidade superior à máxima permitida"], correctAnswer: 0, category: "Legislação", explanation: "O CTB estabelece que é dever dar passagem pela esquerda quando solicitado." },
  { id: 3, text: "Onde não houver sinalização, a velocidade máxima em vias rurais (pista dupla) para automóveis é:", options: ["100 km/h", "110 km/h", "90 km/h", "80 km/h"], correctAnswer: 1, category: "Legislação" },
  { id: 4, text: "A placa A-13a indica:", options: ["Confluência à esquerda", "Entroncamento oblíquo à esquerda", "Curva acentuada à esquerda", "Pista lateral à esquerda"], correctAnswer: 0, category: "Sinalização" },
  { id: 5, text: "O cinto de segurança é obrigatório para:", options: ["Apenas o condutor", "Condutor e passageiros do banco dianteiro", "Todos os ocupantes do veículo", "Apenas em rodovias"], correctAnswer: 2, category: "Legislação" },
  { id: 6, text: "A CNH tem validade de quantos anos para condutores com menos de 50 anos?", options: ["5 anos", "3 anos", "10 anos", "15 anos"], correctAnswer: 2, category: "Legislação" },
  { id: 7, text: "O IPVA é um imposto:", options: ["Municipal", "Federal", "Estadual", "Internacional"], correctAnswer: 2, category: "Legislação" },
  { id: 8, text: "Para conduzir veículo de carga perigosa, é necessário:", options: ["Curso MOPP e ser maior de 21 anos", "Apenas CNH B", "Apenas CNH C", "Ser maior de 18 anos"], correctAnswer: 0, category: "Legislação" },
  { id: 9, text: "A placa R-2 regulamenta:", options: ["Dê a preferência", "Parada obrigatória", "Sentido proibido", "Siga em frente"], correctAnswer: 0, category: "Sinalização" },
  { id: 10, text: "A renovação da CNH para condutores com mais de 70 anos ocorre a cada:", options: ["5 anos", "3 anos", "2 anos", "1 ano"], correctAnswer: 1, category: "Legislação" },
  { id: 11, text: "Qual a cor da sinalização horizontal que divide fluxos de sentidos opostos?", options: ["Branca", "Amarela", "Azul", "Vermelha"], correctAnswer: 1, category: "Sinalização" },
  { id: 12, text: "Dirigir com a CNH vencida há mais de 30 dias é infração:", options: ["Leve", "Média", "Grave", "Gravíssima"], correctAnswer: 3, category: "Infrações" },
  { id: 13, text: "A placa R-6a proíbe:", options: ["Virar à esquerda", "Estacionar", "Parar", "Ultrapassar"], correctAnswer: 1, category: "Sinalização" },
  { id: 14, text: "O condutor habilitado na categoria B pode dirigir:", options: ["Motos", "Ônibus", "Veículos de até 3.500kg de PBT e 8 passageiros", "Caminhões"], correctAnswer: 2, category: "Legislação" },
  { id: 15, text: "Ultrapassar pela contramão em linha contínua amarela é infração:", options: ["Grave", "Média", "Leve", "Gravíssima"], correctAnswer: 3, category: "Infrações" },
  { id: 16, text: "A placa de advertência A-1b indica:", options: ["Curva acentuada à direita", "Curva à direita", "Pista sinuosa", "Curva em S"], correctAnswer: 0, category: "Sinalização" },
  { id: 17, text: "Veículos de prestação de socorro têm prioridade:", options: ["Sempre", "Apenas quando estiverem com sirene e luzes ligadas", "Apenas em rodovias", "Nunca"], correctAnswer: 1, category: "Legislação" },
  { id: 18, text: "Estacionar o veículo em fila dupla é infração:", options: ["Leve", "Média", "Grave", "Gravíssima"], correctAnswer: 2, category: "Infrações" },
  { id: 19, text: "A placa R-19 regulamenta:", options: ["Velocidade máxima permitida", "Velocidade mínima", "Peso máximo", "Altura máxima"], correctAnswer: 0, category: "Sinalização" },
  { id: 20, text: "O condutor que avança o sinal vermelho comete infração:", options: ["Grave", "Gravíssima", "Média", "Leve"], correctAnswer: 1, category: "Infrações" },
  { id: 21, text: "A categoria D habilita o condutor a dirigir:", options: ["Motos", "Veículos de transporte de passageiros (+8 lugares)", "Cargas perigosas apenas", "Trens"], correctAnswer: 1, category: "Legislação" },
  { id: 22, text: "A placa A-32b adverte sobre:", options: ["Passagem de pedestres", "Área escolar", "Passagem sinalizada de pedestres", "Crianças"], correctAnswer: 2, category: "Sinalização" },
  { id: 23, text: "Qual órgão é responsável por emitir a CNH?", options: ["DENATRAN", "DETRAN", "CONTRAN", "CETRAN"], correctAnswer: 1, category: "Legislação" },
  { id: 24, text: "Transitar pelo acostamento é permitido:", options: ["Para ultrapassar", "Quando o trânsito está lento", "Apenas para acessar lotes lindeiros ou em emergência", "Nunca"], correctAnswer: 2, category: "Legislação" },
  { id: 25, text: "A placa R-24a indica:", options: ["Sentido de circulação da via", "Passagem obrigatória", "Siga em frente", "Vire à direita"], correctAnswer: 0, category: "Sinalização" },
  { id: 26, text: "Menores de 10 anos devem ser transportados:", options: ["No banco da frente", "No banco traseiro com dispositivo de retenção adequado", "No colo de um adulto", "Em qualquer lugar"], correctAnswer: 1, category: "Legislação" },
  { id: 27, text: "Usar buzina prolongada e sucessivamente a qualquer pretexto é infração:", options: ["Leve", "Média", "Grave", "Gravíssima"], correctAnswer: 0, category: "Infrações" },
  { id: 28, text: "A placa A-42a indica:", options: ["Início de pista dupla", "Fim de pista dupla", "Pista dividida", "Mão dupla adiante"], correctAnswer: 0, category: "Sinalização" },
  { id: 29, text: "Qual a pontuação para infração Grave?", options: ["3 pontos", "4 pontos", "5 pontos", "7 pontos"], correctAnswer: 2, category: "Legislação" },
  { id: 30, text: "Dirigir ameaçando os pedestres é infração:", options: ["Grave", "Média", "Leve", "Gravíssima"], correctAnswer: 3, category: "Infrações" },
  { id: 31, text: "A placa R-4a proíbe:", options: ["Virar à direita", "Virar à esquerda", "Seguir em frente", "Retornar"], correctAnswer: 1, category: "Sinalização" },
  { id: 32, text: "É considerado crime de trânsito:", options: ["Estacionar na calçada", "Avançar sinal vermelho", "Dirigir embriagado (alcoolemia superior a 0,3mg/L)", "Parar em fila dupla"], correctAnswer: 2, category: "Legislação" },
  { id: 33, text: "A placa A-18 salienta:", options: ["Saliência ou lombada", "Depressão", "Pista irregular", "Declive acentuado"], correctAnswer: 0, category: "Sinalização" },
  { id: 34, text: "Recusar-se a fazer o teste do bafômetro acarreta:", options: ["Multa leve", "Apenas advertência", "Multa gravíssima (fator x10) e suspensão da CNH", "Nenhuma penalidade"], correctAnswer: 2, category: "Infrações" },
  { id: 35, text: "A placa R-10 proíbe:", options: ["Trânsito de veículos automotores", "Trânsito de pedestres", "Trânsito de bicicletas", "Trânsito de caminhões"], correctAnswer: 0, category: "Sinalização" },
  { id: 36, text: "Veículos de carga que excedam as dimensões devem portar:", options: ["AET (Autorização Especial de Trânsito)", "Apenas nota fiscal", "Carteira D", "Nada específico"], correctAnswer: 0, category: "Legislação" },
  { id: 37, text: "A sinalização semafórica de advertência tem a cor:", options: ["Vermelha", "Amarela", "Verde", "Azul"], correctAnswer: 1, category: "Sinalização" },
  { id: 38, text: "Deixar de prestar socorro à vítima quando possível é:", options: ["Infração de trânsito e crime", "Apenas falta de educação", "Infração leve", "Permitido se estiver com pressa"], correctAnswer: 0, category: "Legislação" },
  { id: 39, text: "A placa R-25a exige:", options: ["Vire à esquerda", "Vire à direita", "Siga em frente", "Curva à esquerda"], correctAnswer: 0, category: "Sinalização" },
  { id: 40, text: "O DPVAT é o seguro que indeniza:", options: ["Danos materiais do veículo", "Danos pessoais causados por veículos automotores", "Roubo do veículo", "Multas de trânsito"], correctAnswer: 1, category: "Legislação" },

  // --- DIREÇÃO DEFENSIVA (41-70) ---
  { id: 41, text: "A chuva reduz a visibilidade e aderência. O condutor deve:", options: ["Aumentar a velocidade", "Acionar pisca-alerta em movimento", "Reduzir velocidade e aumentar distância", "Desligar faróis"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 42, text: "O que é aquaplanagem?", options: ["Perda de contato do pneu com o solo por água", "Falta de freio", "Travamento das rodas", "Derrapagem em areia"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 43, text: "O tempo de reação médio de um condutor é de:", options: ["3 segundos", "0,75 a 1 segundo", "5 segundos", "10 segundos"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 44, text: "A distância percorrida entre a visualização do perigo e a parada total é:", options: ["Distância de reação", "Distância de frenagem", "Distância de parada", "Distância de seguimento"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 45, text: "Ofuscamento e penumbra são condições adversas de:", options: ["Luz", "Tempo", "Via", "Veículo"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 46, text: "O cinto de segurança deve ser usado:", options: ["Folgado", "Com presilhas", "Justo ao corpo e sem dobras", "Passando pelo pescoço"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 47, text: "Para evitar colisão com o veículo da frente, deve-se manter:", options: ["Distância de seguimento", "Distância de frenagem", "Distância de reação", "Distância lateral"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 48, text: "Em neblina intensa, deve-se usar:", options: ["Luz alta", "Luz baixa ou farol de neblina", "Pisca-alerta ligado", "Faróis desligados"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 49, text: "O encosto de cabeça serve para evitar:", options: ["Conforto apenas", "O efeito chicote em colisões traseiras", "Dores nas costas", "Que o passageiro durma"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 50, text: "A ergonomia no trânsito estuda:", options: ["A mecânica do carro", "A interação homem-máquina-meio", "As leis de trânsito", "O clima"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 51, text: "Em declives acentuados (descidas), deve-se:", options: ["Descer em ponto morto (banguela)", "Desligar o motor", "Descer engrenado", "Pisar na embreagem"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 52, text: "Ao cruzar com veículo com luz alta, você deve:", options: ["Acender a luz alta também", "Piscar o farol e desviar o olhar para a direita", "Fechar os olhos", "Buzinar"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 53, text: "Subesterçamento é quando o veículo:", options: ["Perde aderência nas rodas traseiras", "Perde aderência nas rodas dianteiras (sai de frente)", "Capota", "Para de funcionar"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 54, text: "Sobresterçamento é quando o veículo:", options: ["Perde aderência nas rodas traseiras (sai de traseira)", "Sai de frente", "Fica sem freio", "Fura o pneu"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 55, text: "Os espelhos retrovisores devem ser ajustados:", options: ["Com o veículo em movimento", "Antes de iniciar o deslocamento", "Apenas pelo passageiro", "Não precisam de ajuste"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 56, text: "Para realizar uma ultrapassagem segura, o condutor deve:", options: ["Sinalizar e certificar-se de que há espaço", "Colar no veículo da frente", "Ultrapassar em curvas", "Não sinalizar"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 57, text: "O freio ABS serve para:", options: ["Travar as rodas", "Evitar o travamento das rodas na frenagem", "Aumentar a velocidade", "Reduzir o consumo"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 58, text: "A força centrífuga tende a jogar o veículo:", options: ["Para dentro da curva", "Para fora da curva", "Para cima", "Para trás"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 59, text: "O estado de conservação dos pneus é condição adversa de:", options: ["Veículo", "Via", "Condutor", "Tempo"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 60, text: "Fadiga, sono e álcool são condições adversas do:", options: ["Veículo", "Condutor", "Passageiro", "Pedestre"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 61, text: "Ao ver uma bola rolando para a rua, o condutor deve:", options: ["Acelerar", "Buzinar", "Reduzir a velocidade e preparar para parar", "Desviar bruscamente"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 62, text: "Em ventos fortes laterais, o condutor deve:", options: ["Acelerar", "Abrir as janelas", "Segurar firme o volante e reduzir a velocidade", "Fechar os olhos"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 63, text: "A principal causa de acidentes é:", options: ["Falha mecânica", "Falha humana", "Má conservação da via", "Clima"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 64, text: "Dirigir defensivamente significa:", options: ["Dirigir devagar", "Dirigir com medo", "Dirigir de modo a evitar acidentes, apesar dos erros dos outros", "Dirigir apenas em dia de sol"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 65, text: "O uso do celular ao volante causa:", options: ["Melhor atenção", "Distração visual e cognitiva", "Maior segurança", "Nenhum risco"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 66, text: "O 'ponto cego' é:", options: ["Área não visível pelos retrovisores", "Farol quebrado", "Vidro sujo", "Olho do condutor"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 67, text: "Em ciclomotores, o capacete é:", options: ["Opcional", "Obrigatório apenas na rodovia", "Obrigatório com viseira ou óculos de proteção", "Dispensável"], correctAnswer: 2, category: "Direção Defensiva" },
  { id: 68, text: "A regra dos dois segundos serve para:", options: ["Calcular a distância de seguimento", "Medir o óleo", "Trocar a marcha", "Ligar o carro"], correctAnswer: 0, category: "Direção Defensiva" },
  { id: 69, text: "Ao passar por poças d'água, deve-se:", options: ["Acelerar forte", "Segurar firme o volante e não frear bruscamente", "Frear forte", "Virar o volante"], correctAnswer: 1, category: "Direção Defensiva" },
  { id: 70, text: "Motociclistas devem trafegar:", options: ["No corredor sempre", "Na calçada", "No centro da faixa de trânsito", "Na contramão"], correctAnswer: 2, category: "Direção Defensiva" },

  // --- PRIMEIROS SOCORROS (71-90) ---
  { id: 71, text: "Em caso de hemorragia externa:", options: ["Fazer torniquete", "Dar água", "Comprimir o local com pano limpo", "Jogar pó de café"], correctAnswer: 2, category: "Primeiros Socorros" },
  { id: 72, text: "Ao se deparar com acidente, a 1ª atitude é:", options: ["Sinalizar o local", "Remover vítimas", "Fugir", "Discutir"], correctAnswer: 0, category: "Primeiros Socorros" },
  { id: 73, text: "Se a vítima de acidente motociclístico estiver de capacete:", options: ["Deve-se retirar o capacete", "Não retirar o capacete, salvo necessidade extrema de RCP", "Folgar a jugular apenas", "Pedir para ela tirar"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 74, text: "Em caso de fratura exposta:", options: ["Tentar colocar o osso no lugar", "Proteger o ferimento com pano limpo e imobilizar", "Puxar o membro", "Passar pomada"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 75, text: "O número do SAMU é:", options: ["190", "192", "193", "191"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 76, text: "O número do Corpo de Bombeiros é:", options: ["190", "192", "193", "181"], correctAnswer: 2, category: "Primeiros Socorros" },
  { id: 77, text: "Em parada cardiorrespiratória, deve-se:", options: ["Fazer compressões torácicas", "Dar tapas nas costas", "Jogar água fria", "Esperar acordar"], correctAnswer: 0, category: "Primeiros Socorros" },
  { id: 78, text: "Vítima com objeto encravado no corpo:", options: ["Retirar o objeto imediatamente", "Não retirar o objeto e estabilizar", "Cortar o objeto", "Girar o objeto"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 79, text: "Sinalizar o local do acidente evita:", options: ["Novos acidentes", "Multas", "Engarrafamento", "Chuvas"], correctAnswer: 0, category: "Primeiros Socorros" },
  { id: 80, text: "Para sinalizar acidente em via de 80km/h (pista seca):", options: ["40 passos", "80 passos longos", "10 passos", "200 passos"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 81, text: "Vítima em estado de choque apresenta:", options: ["Pele fria, pálida e pulso fraco", "Rosto vermelho e quente", "Euforia", "Fome excessiva"], correctAnswer: 0, category: "Primeiros Socorros" },
  { id: 82, text: "Em queimaduras, deve-se aplicar:", options: ["Pasta de dente", "Óleo", "Água corrente limpa", "Gelo direto"], correctAnswer: 2, category: "Primeiros Socorros" },
  { id: 83, text: "Se houver risco de incêndio no veículo acidentado:", options: ["Jogar terra", "Afastar as pessoas e, se possível, usar extintor", "Jogar álcool", "Soprar"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 84, text: "Movimentar a vítima sem técnica pode causar:", options: ["Melhora na dor", "Lesão na medula (tetraplegia)", "Conforto", "Cura da fratura"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 85, text: "A omissão de socorro é considerada:", options: ["Crime e infração", "Apenas infração administrativa", "Permitida à noite", "Eticamente aceitável"], correctAnswer: 0, category: "Primeiros Socorros" },
  { id: 86, text: "Para verificar a respiração, deve-se:", options: ["Ver, ouvir e sentir", "Chacoalhar a vítima", "Gritar", "Jogar água"], correctAnswer: 0, category: "Primeiros Socorros" },
  { id: 87, text: "Em convulsão, deve-se:", options: ["Segurar a língua da vítima", "Proteger a cabeça e afastar objetos", "Dar água com açúcar", "Prender os braços"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 88, text: "O torniquete é recomendado:", options: ["Para qualquer sangramento", "Apenas em amputações ou hemorragias incontroláveis nos membros", "Nunca", "Para picada de cobra"], correctAnswer: 1, category: "Primeiros Socorros" },
  { id: 89, text: "Se a vítima sentir sede:", options: ["Dar água", "Dar refrigerante", "Não dar líquidos (jejum para possível cirurgia)", "Dar suco"], correctAnswer: 2, category: "Primeiros Socorros" },
  { id: 90, text: "O triângulo de segurança deve ser colocado:", options: ["Em cima do carro", "A uma distância segura antes do acidente", "No acostamento apenas", "Na frente do carro"], correctAnswer: 1, category: "Primeiros Socorros" },

  // --- MECÂNICA BÁSICA (91-105) ---
  { id: 91, text: "A manutenção preventiva ajuda a:", options: ["Aumentar consumo", "Evitar acidentes e reduzir poluentes", "Aumentar ruído", "Gastar mais"], correctAnswer: 1, category: "Mecânica" },
  { id: 92, text: "O sistema de arrefecimento serve para:", options: ["Esquentar o motor", "Controlar a temperatura do motor", "Frear o carro", "Limpar o vidro"], correctAnswer: 1, category: "Mecânica" },
  { id: 93, text: "O freio de estacionamento (mão) atua geralmente:", options: ["Nas rodas dianteiras", "Nas rodas traseiras", "No cardã", "Na transmissão"], correctAnswer: 1, category: "Mecânica" },
  { id: 94, text: "A finalidade do óleo lubrificante é:", options: ["Refrigerar apenas", "Reduzir o atrito e desgaste das peças móveis", "Dar partida", "Limpar o escapamento"], correctAnswer: 1, category: "Mecânica" },
  { id: 95, text: "Pneus carecas (sulcos < 1,6mm) causam:", options: ["Economia", "Perda de aderência e risco de aquaplanagem", "Mais conforto", "Menos ruído"], correctAnswer: 1, category: "Mecânica" },
  { id: 96, text: "O extintor de incêndio (quando obrigatório) é do tipo:", options: ["ABC", "Água", "Espuma", "CO2 apenas"], correctAnswer: 0, category: "Mecânica" },
  { id: 97, text: "A bateria do veículo serve para:", options: ["Armazenar energia elétrica", "Gerar energia", "Resfriar o motor", "Filtrar o ar"], correctAnswer: 0, category: "Mecânica" },
  { id: 98, text: "O alternador serve para:", options: ["Carregar a bateria e alimentar o sistema elétrico", "Dar a partida", "Trocar marchas", "Medir combustível"], correctAnswer: 0, category: "Mecânica" },
  { id: 99, text: "Se a luz do óleo acender no painel:", options: ["Seguir viagem", "Parar imediatamente e verificar nível", "Acelerar", "Ligar o rádio"], correctAnswer: 1, category: "Mecânica" },
  { id: 100, text: "O catalisador serve para:", options: ["Aumentar potência", "Reduzir emissão de gases poluentes", "Resfriar", "Filtrar óleo"], correctAnswer: 1, category: "Mecânica" },
  { id: 101, text: "O filtro de ar sujo causa:", options: ["Aumento do consumo de combustível", "Melhora no desempenho", "Economia", "Menos fumaça"], correctAnswer: 0, category: "Mecânica" },
  { id: 102, text: "A mistura ar-combustível é feita pelo:", options: ["Injeção eletrônica ou carburador", "Radiador", "Alternador", "Freio"], correctAnswer: 0, category: "Mecânica" },
  { id: 103, text: "O balanceamento das rodas serve para:", options: ["Evitar trepidações na direção", "Alinhar a direção", "Frear melhor", "Economizar luz"], correctAnswer: 0, category: "Mecânica" },
  { id: 104, text: "O alinhamento serve para:", options: ["Evitar desgaste irregular dos pneus e puxada na direção", "Evitar trepidação", "Aumentar potência", "Limpar pneus"], correctAnswer: 0, category: "Mecânica" },
  { id: 105, text: "Fluido de freio baixo pode indicar:", options: ["Vazamento ou desgaste das pastilhas", "Motor fundido", "Falta de gasolina", "Pneu furado"], correctAnswer: 0, category: "Mecânica" },

  // --- MEIO AMBIENTE E CIDADANIA (106-120) ---
  { id: 106, text: "O órgão responsável por controlar a emissão de poluentes é:", options: ["CONAMA", "DETRAN", "CONTRAN", "DNIT"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 107, text: "A poluição sonora causa:", options: ["Irritabilidade e estresse", "Bem-estar", "Melhora na audição", "Calma"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 108, text: "Jogar lixo na via é infração:", options: ["Média", "Leve", "Grave", "Gravíssima"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 109, text: "O canister serve para:", options: ["Absorver vapores de combustível", "Filtrar água", "Limpar o ar", "Resfriar"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 110, text: "A inspeção veicular ajuda a:", options: ["Controlar a emissão de gases e segurança", "Aumentar impostos", "Vender carros", "Multar apenas"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 111, text: "Dirigir defensivamente contribui para o meio ambiente pois:", options: ["Economiza combustível e pneus", "Gasta mais", "Polui mais", "Atrasa a viagem"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 112, text: "Substância que sai do escapamento e é letal em locais fechados:", options: ["Monóxido de Carbono", "Oxigênio", "Nitrogênio", "Vapor d'água"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 113, text: "Cidadania no trânsito é:", options: ["Respeitar direitos e deveres", "Disputar espaço", "Xingar os outros", "Andar rápido"], correctAnswer: 0, category: "Cidadania" },
  { id: 114, text: "O convívio social no trânsito deve ser pautado em:", options: ["Solidariedade e respeito", "Individualismo", "Agressividade", "Pressa"], correctAnswer: 0, category: "Cidadania" },
  { id: 115, text: "A poluição visual pode:", options: ["Desviar a atenção do condutor", "Ajudar na direção", "Melhorar a paisagem", "Acalmar"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 116, text: "O chorume é resíduo de:", options: ["Lixo orgânico decomposto", "Óleo", "Bateria", "Pneu"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 117, text: "Para descartar bateria velha, deve-se:", options: ["Devolver ao revendedor ou fabricante", "Jogar no lixo comum", "Jogar no rio", "Queimar"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 118, text: "Pneus velhos abandonados acumulam:", options: ["Água e criam mosquitos", "Terra", "Ar puro", "Nada"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 119, text: "O excesso de ruído do motor deve ser controlado pelo:", options: ["Silenciador do escapamento", "Radiador", "Freio", "Carburador"], correctAnswer: 0, category: "Meio Ambiente" },
  { id: 120, text: "A educação para o trânsito é direito de:", options: ["Todos", "Apenas motoristas", "Apenas crianças", "Apenas pedestres"], correctAnswer: 0, category: "Cidadania" }
];